remote_theme: saifkhichi96/simple-material
url: 'https://saifkhichi96.github.io'
baseurl: ''

permalink: /:title/

defaults:
  -
    scope:
      path: ''
    values:
      layout: page
      syntax: true

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE